# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35399919dd15b1eeec0f64e5ced5d600d47f3193745018ad30f5d723602c79086a70c8007f352f9932ec432f00bb9888f75ba22b75925f4d3987dbe912ea6949

test:
  secret_key_base: 9a003d9809e7fbb0bf1db7874e1e524a5751cd03a07dfac4b69e00e9f4ead4accf135717b777e4fc5e3f4ea5ab7805858e75b03fd7bc4565e1e37a6caab3d01c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
